secret_key_base: R_A-ICRjGeY-3FTHNWcNHdvkp_TWdKwRnS4KF_JGTQ8
port: 3000
name: project_ci

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password
  context:
    - request
    - session
    - headers
    - cookies
    - params

host: 0.0.0.0
port_reuse: true
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://localhost:6379"
database_url: "postgres://admin:password@db:5432/project_ci_development"
# database_url: postgres://postgres:@localhost:5432/project_ci_development
auto_reload: true

session:
  key: amber.session
  store: signed_cookie
  expires: 0

smtp:
  enabled: false

secrets:
  description: Store your development secrets credentials and settings here.
